#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/oneplus/giulia

PRODUCT_COPY_FILES += \
    vendor/oneplus/giulia/proprietary/odm/etc/acdbdata/Audio_Parameter_Version.txt:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/Audio_Parameter_Version.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/acdbdata/FTM/acdb_cal.acdb:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/FTM/acdb_cal.acdb \
    vendor/oneplus/giulia/proprietary/odm/etc/acdbdata/FTM/workspaceFileXml.qwsp:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/FTM/workspaceFileXml.qwsp \
    vendor/oneplus/giulia/proprietary/odm/etc/acdbdata/acdb_cal.acdb:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/acdb_cal.acdb \
    vendor/oneplus/giulia/proprietary/odm/etc/acdbdata/up_ve_enpuv4_ha.eai:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/up_ve_enpuv4_ha.eai \
    vendor/oneplus/giulia/proprietary/odm/etc/acdbdata/up_ve_enpuv4_hh.eai:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/up_ve_enpuv4_hh.eai \
    vendor/oneplus/giulia/proprietary/odm/etc/audio/audiox_param/HP_COMMON.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/HP_COMMON.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/audio/audiox_param/HP_GAME1.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/HP_GAME1.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/audio/audiox_param/HP_GAME2.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/HP_GAME2.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/audio/audiox_param/HP_MOVIE.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/HP_MOVIE.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/audio/audiox_param/HP_MOVIE2.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/HP_MOVIE2.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/audio/audiox_param/HP_MUSIC.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/HP_MUSIC.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/audio/audiox_param/HP_VOICE.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/HP_VOICE.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/audio/audiox_param/SPK_COMMON_lvl1.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_COMMON_lvl1.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/audio/audiox_param/SPK_COMMON_lvl2.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_COMMON_lvl2.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/audio/audiox_param/SPK_COMMON_lvl3.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_COMMON_lvl3.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/audio/audiox_param/SPK_COMMON_lvl4.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_COMMON_lvl4.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/audio/audiox_param/SPK_COMMON_lvl5.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_COMMON_lvl5.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/audio/audiox_param/SPK_GAME1_lvl1.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_GAME1_lvl1.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/audio/audiox_param/SPK_GAME1_lvl2.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_GAME1_lvl2.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/audio/audiox_param/SPK_GAME1_lvl3.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_GAME1_lvl3.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/audio/audiox_param/SPK_GAME1_lvl4.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_GAME1_lvl4.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/audio/audiox_param/SPK_GAME1_lvl5.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_GAME1_lvl5.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/audio/audiox_param/SPK_GAME2_lvl1.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_GAME2_lvl1.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/audio/audiox_param/SPK_GAME2_lvl2.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_GAME2_lvl2.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/audio/audiox_param/SPK_GAME2_lvl3.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_GAME2_lvl3.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/audio/audiox_param/SPK_GAME2_lvl4.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_GAME2_lvl4.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/audio/audiox_param/SPK_GAME2_lvl5.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_GAME2_lvl5.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/audio/audiox_param/SPK_MOVIE2_lvl1.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_MOVIE2_lvl1.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/audio/audiox_param/SPK_MOVIE2_lvl2.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_MOVIE2_lvl2.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/audio/audiox_param/SPK_MOVIE2_lvl3.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_MOVIE2_lvl3.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/audio/audiox_param/SPK_MOVIE2_lvl4.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_MOVIE2_lvl4.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/audio/audiox_param/SPK_MOVIE2_lvl5.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_MOVIE2_lvl5.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/audio/audiox_param/SPK_MOVIE_lvl1.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_MOVIE_lvl1.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/audio/audiox_param/SPK_MOVIE_lvl2.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_MOVIE_lvl2.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/audio/audiox_param/SPK_MOVIE_lvl3.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_MOVIE_lvl3.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/audio/audiox_param/SPK_MOVIE_lvl4.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_MOVIE_lvl4.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/audio/audiox_param/SPK_MOVIE_lvl5.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_MOVIE_lvl5.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/audio/audiox_param/SPK_MUSIC_lvl1.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_MUSIC_lvl1.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/audio/audiox_param/SPK_MUSIC_lvl2.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_MUSIC_lvl2.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/audio/audiox_param/SPK_MUSIC_lvl3.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_MUSIC_lvl3.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/audio/audiox_param/SPK_MUSIC_lvl4.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_MUSIC_lvl4.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/audio/audiox_param/SPK_MUSIC_lvl5.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_MUSIC_lvl5.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/audio/audiox_param/SPK_VOICE_lvl1.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_VOICE_lvl1.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/audio/audiox_param/SPK_VOICE_lvl2.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_VOICE_lvl2.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/audio/audiox_param/SPK_VOICE_lvl3.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_VOICE_lvl3.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/audio/audiox_param/SPK_VOICE_lvl4.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_VOICE_lvl4.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/audio/audiox_param/SPK_VOICE_lvl5.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/audiox_param/SPK_VOICE_lvl5.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/BodySeg.json:$(TARGET_COPY_OUT_ODM)/etc/camera/BodySeg.json \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/CaliData/mtStereoParams_golden.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/CaliData/mtStereoParams_golden.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/CaliData/mwStereoParams_golden.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/CaliData/mwStereoParams_golden.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/CameraHWConfiguration.config:$(TARGET_COPY_OUT_ODM)/etc/camera/CameraHWConfiguration.config \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/aigc/aigc_models/blurDet_sm8650.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/aigc/aigc_models/blurDet_sm8650.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/aigc/aigc_models/faceSeg_sm8650.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/aigc/aigc_models/faceSeg_sm8650.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/aigc/aigc_models/gfpgan1024_sm8650.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/aigc/aigc_models/gfpgan1024_sm8650.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/aigc/aigc_models/noise300.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/aigc/aigc_models/noise300.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/aigc/libs/libODNN.so:$(TARGET_COPY_OUT_ODM)/etc/camera/aigc/libs/libODNN.so \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/aigc/libs/libOPAlgoCamAIGCFace.so:$(TARGET_COPY_OUT_ODM)/etc/camera/aigc/libs/libOPAlgoCamAIGCFace.so \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/aigc/libs/libQnnHtp.so:$(TARGET_COPY_OUT_ODM)/etc/camera/aigc/libs/libQnnHtp.so \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/aigc/libs/libQnnHtpV75Stub.so:$(TARGET_COPY_OUT_ODM)/etc/camera/aigc/libs/libQnnHtpV75Stub.so \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/aigc/libs/libQnnSystem.so:$(TARGET_COPY_OUT_ODM)/etc/camera/aigc/libs/libQnnSystem.so \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/aigc/libs/libzlib.so:$(TARGET_COPY_OUT_ODM)/etc/camera/aigc/libs/libzlib.so \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/arcsat_fusion.config:$(TARGET_COPY_OUT_ODM)/etc/camera/arcsat_fusion.config \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/arcsoft_eis_configure:$(TARGET_COPY_OUT_ODM)/etc/camera/arcsoft_eis_configure \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/basictone/odt/ODT_Dolby:$(TARGET_COPY_OUT_ODM)/etc/camera/basictone/odt/ODT_Dolby \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/basictone/odt/ODT_Photo:$(TARGET_COPY_OUT_ODM)/etc/camera/basictone/odt/ODT_Photo \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/basictone/odt/ODT_Pre:$(TARGET_COPY_OUT_ODM)/etc/camera/basictone/odt/ODT_Pre \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/basictone/odt/ODT_Video:$(TARGET_COPY_OUT_ODM)/etc/camera/basictone/odt/ODT_Video \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/camera_engmode.xml:$(TARGET_COPY_OUT_ODM)/etc/camera/camera_engmode.xml \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/cfr_bin/CFR_OPlus_EF017_UW_snapshot.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/cfr_bin/CFR_OPlus_EF017_UW_snapshot.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/cfr_bin/CFR_imx355.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/cfr_bin/CFR_imx355.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/cfr_bin/CFR_imx906.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/cfr_bin/CFR_imx906.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/cfr_bin/CFR_s5kjn5_giulia.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/cfr_bin/CFR_s5kjn5_giulia.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/conf_tuning_params.json:$(TARGET_COPY_OUT_ODM)/etc/camera/conf_tuning_params.json \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/config/camera_unit_config:$(TARGET_COPY_OUT_ODM)/etc/camera/config/camera_unit_config \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/config/camera_unit_feature_config.protobuf:$(TARGET_COPY_OUT_ODM)/etc/camera/config/camera_unit_feature_config.protobuf \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/config/imx355:$(TARGET_COPY_OUT_ODM)/etc/camera/config/imx355 \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/config/imx480:$(TARGET_COPY_OUT_ODM)/etc/camera/config/imx480 \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/config/imx906:$(TARGET_COPY_OUT_ODM)/etc/camera/config/imx906 \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/config/oplus_camera_algo_switch_config:$(TARGET_COPY_OUT_ODM)/etc/camera/config/oplus_camera_algo_switch_config \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/config/oplus_camera_algo_traversal_config.json:$(TARGET_COPY_OUT_ODM)/etc/camera/config/oplus_camera_algo_traversal_config.json \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/config/oplus_camera_aps_config:$(TARGET_COPY_OUT_ODM)/etc/camera/config/oplus_camera_aps_config \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/config/oplus_camera_config:$(TARGET_COPY_OUT_ODM)/etc/camera/config/oplus_camera_config \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/config/oplus_camera_preview_decision_config.json:$(TARGET_COPY_OUT_ODM)/etc/camera/config/oplus_camera_preview_decision_config.json \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/config/oplus_preview_decision_params.json:$(TARGET_COPY_OUT_ODM)/etc/camera/config/oplus_preview_decision_params.json \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/config/pickref_params.xml:$(TARGET_COPY_OUT_ODM)/etc/camera/config/pickref_params.xml \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/config/quick_visibility_white_list:$(TARGET_COPY_OUT_ODM)/etc/camera/config/quick_visibility_white_list \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/config/s5kjn5_giulia:$(TARGET_COPY_OUT_ODM)/etc/camera/config/s5kjn5_giulia \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/config/video_beauty_default_config:$(TARGET_COPY_OUT_ODM)/etc/camera/config/video_beauty_default_config \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/dng/ColorMatrix1_imx581_2.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/dng/ColorMatrix1_imx581_2.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/dng/ColorMatrix1_imx709_3.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/dng/ColorMatrix1_imx709_3.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/dng/ColorMatrix1_imx890_0.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/dng/ColorMatrix1_imx890_0.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/dng/ColorMatrix2_imx581_2.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/dng/ColorMatrix2_imx581_2.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/dng/ColorMatrix2_imx709_3.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/dng/ColorMatrix2_imx709_3.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/dng/ColorMatrix2_imx890_0.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/dng/ColorMatrix2_imx890_0.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/dng/D28HUESATMap_imx581_2.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/dng/D28HUESATMap_imx581_2.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/dng/D28HUESATMap_imx709_3.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/dng/D28HUESATMap_imx709_3.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/dng/D28HUESATMap_imx890_0.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/dng/D28HUESATMap_imx890_0.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/dng/D65HUESATMap_imx581_2.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/dng/D65HUESATMap_imx581_2.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/dng/D65HUESATMap_imx709_3.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/dng/D65HUESATMap_imx709_3.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/dng/D65HUESATMap_imx890_0.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/dng/D65HUESATMap_imx890_0.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/dng/ToneCurve_imx581_2.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/dng/ToneCurve_imx581_2.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/dng/ToneCurve_imx709_3.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/dng/ToneCurve_imx709_3.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/dng/ToneCurve_imx890_0.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/dng/ToneCurve_imx890_0.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/facerestore/InitParams.json:$(TARGET_COPY_OUT_ODM)/etc/camera/facerestore/InitParams.json \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/facerestore/fr_models/BDET.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/facerestore/fr_models/BDET.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/facerestore/fr_models/DB.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/facerestore/fr_models/DB.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/facerestore/fr_models/FS.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/facerestore/fr_models/FS.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/facerestore/fr_models/F_C.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/facerestore/fr_models/F_C.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/facerestore/fr_models/F_SE_A.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/facerestore/fr_models/F_SE_A.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/facerestore/fr_models/F_SE_B.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/facerestore/fr_models/F_SE_B.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/facerestore/fr_models/F_SL_A.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/facerestore/fr_models/F_SL_A.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/facerestore/fr_models/F_SL_B.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/facerestore/fr_models/F_SL_B.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/facerestore/fr_models/RM_SE_A.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/facerestore/fr_models/RM_SE_A.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/facerestore/fr_models/RM_SE_B.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/facerestore/fr_models/RM_SE_B.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/facerestore/fr_models/RM_SE_C.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/facerestore/fr_models/RM_SE_C.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/facerestore/fr_models/RM_SL_A.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/facerestore/fr_models/RM_SL_A.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/facerestore/fr_models/RM_SL_B.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/facerestore/fr_models/RM_SL_B.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/facerestore/fr_models/RM_SL_C.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/facerestore/fr_models/RM_SL_C.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/facerestore/fr_models/RT_A.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/facerestore/fr_models/RT_A.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/facerestore/fr_models/RT_B.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/facerestore/fr_models/RT_B.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/facerestore/fr_models/RT_C.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/facerestore/fr_models/RT_C.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/facerestore/fr_models/RT_D.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/facerestore/fr_models/RT_D.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/facerestore/fr_models/RT_E.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/facerestore/fr_models/RT_E.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/facerestore/fr_models/faceRestoreSnapMask.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/facerestore/fr_models/faceRestoreSnapMask.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/facesr_hd_composite_ff_4.3.20_qcom8650_qnn_segqnn_qnn2.13.1_qualitybin.model:$(TARGET_COPY_OUT_ODM)/etc/camera/facesr_hd_composite_ff_4.3.20_qcom8650_qnn_segqnn_qnn2.13.1_qualitybin.model \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/fb_model/100_pre.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/100_pre.png \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/fb_model/101_pre.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/101_pre.png \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/fb_model/103_pre.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/103_pre.png \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/fb_model/110_pre.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/110_pre.png \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/fb_model/111_pre.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/111_pre.png \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/fb_model/200_pre.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/200_pre.png \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/fb_model/201_pre.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/201_pre.png \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/fb_model/203_pre.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/203_pre.png \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/fb_model/210_pre.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/210_pre.png \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/fb_model/211_pre.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/211_pre.png \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/fb_model/face_faceshadow_chinese.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/face_faceshadow_chinese.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/filters_lut/LMT_6_D65_33.cube:$(TARGET_COPY_OUT_ODM)/etc/camera/filters_lut/LMT_6_D65_33.cube \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/filters_lut/ODT_2020_PQ10000nits-P3_srgb,roll-off_33_ver5.cube:$(TARGET_COPY_OUT_ODM)/etc/camera/filters_lut/ODT_2020_PQ10000nits-P3_srgb,roll-off_33_ver5.cube \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/filters_lut/VigTab_Main:$(TARGET_COPY_OUT_ODM)/etc/camera/filters_lut/VigTab_Main \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/filters_lut/VigTab_Tele:$(TARGET_COPY_OUT_ODM)/etc/camera/filters_lut/VigTab_Tele \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/filters_lut/VigTab_UTele:$(TARGET_COPY_OUT_ODM)/etc/camera/filters_lut/VigTab_UTele \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/filters_lut/VigTab_Wide:$(TARGET_COPY_OUT_ODM)/etc/camera/filters_lut/VigTab_Wide \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/filters_lut/empty_33.cube:$(TARGET_COPY_OUT_ODM)/etc/camera/filters_lut/empty_33.cube \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/filters_lut/masterlut/FromXml:$(TARGET_COPY_OUT_ODM)/etc/camera/filters_lut/masterlut/FromXml \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/filters_lut/masterlut/LMTLut0:$(TARGET_COPY_OUT_ODM)/etc/camera/filters_lut/masterlut/LMTLut0 \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/filters_lut/masterlut/LMTLut1:$(TARGET_COPY_OUT_ODM)/etc/camera/filters_lut/masterlut/LMTLut1 \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/filters_lut/masterlut/ODT_Photo:$(TARGET_COPY_OUT_ODM)/etc/camera/filters_lut/masterlut/ODT_Photo \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/filters_lut/masterlut/SCLut0:$(TARGET_COPY_OUT_ODM)/etc/camera/filters_lut/masterlut/SCLut0 \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/filters_lut/masterlut/SCLut1:$(TARGET_COPY_OUT_ODM)/etc/camera/filters_lut/masterlut/SCLut1 \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/filters_lut/masterlut/SCLut2:$(TARGET_COPY_OUT_ODM)/etc/camera/filters_lut/masterlut/SCLut2 \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/filters_lut/masterlut/SCLut3:$(TARGET_COPY_OUT_ODM)/etc/camera/filters_lut/masterlut/SCLut3 \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/filters_lut/masterlut/SCLut4:$(TARGET_COPY_OUT_ODM)/etc/camera/filters_lut/masterlut/SCLut4 \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/filters_lut/masterlut/SCLut5:$(TARGET_COPY_OUT_ODM)/etc/camera/filters_lut/masterlut/SCLut5 \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/filters_lut/masterlut/SCLut6:$(TARGET_COPY_OUT_ODM)/etc/camera/filters_lut/masterlut/SCLut6 \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/filters_lut/masterlut/SCLut7:$(TARGET_COPY_OUT_ODM)/etc/camera/filters_lut/masterlut/SCLut7 \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/filters_lut/masterlut/SCLut8:$(TARGET_COPY_OUT_ODM)/etc/camera/filters_lut/masterlut/SCLut8 \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/filters_lut/masterlut/SimTool.ini:$(TARGET_COPY_OUT_ODM)/etc/camera/filters_lut/masterlut/SimTool.ini \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/hybridraw_models/ai_motion_mask.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/ai_motion_mask.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/hybridraw_models/ai_motion_mask_18M.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/ai_motion_mask_18M.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/hybridraw_models/ai_motion_mask_3Div2M.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/ai_motion_mask_3Div2M.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/hybridraw_models/ai_motion_mask_50M.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/ai_motion_mask_50M.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/hybridraw_models/ai_seg_human_landscape.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/ai_seg_human_landscape.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/hybridraw_models/ai_seg_human_portrait.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/ai_seg_human_portrait.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/hybridraw_models/ai_seg_sky_day.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/ai_seg_sky_day.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/hybridraw_models/ai_seg_sky_night.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/ai_seg_sky_night.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/hybridraw_models/gan_enhancer_20x.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/gan_enhancer_20x.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/hybridraw_models/tele_binning_ev0.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/tele_binning_ev0.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/hybridraw_models/tele_binning_ev0_sf.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/tele_binning_ev0_sf.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/hybridraw_models/tele_binning_evm.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/tele_binning_evm.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/hybridraw_models/tele_binning_evmm.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/tele_binning_evmm.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/hybridraw_models/tele_quadbayer_ev0.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/tele_quadbayer_ev0.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/hybridraw_models/tele_quadbayer_evm.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/tele_quadbayer_evm.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/oplus_camera_algo_traversal_config.json:$(TARGET_COPY_OUT_ODM)/etc/camera/oplus_camera_algo_traversal_config.json \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/salient2_seg.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/salient2_seg.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/spectrum_test_data_golden:$(TARGET_COPY_OUT_ODM)/etc/camera/spectrum_test_data_golden \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/wide.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/wide.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/display/cwb_weightspos.json:$(TARGET_COPY_OUT_ODM)/etc/display/cwb_weightspos.json \
    vendor/oneplus/giulia/proprietary/odm/etc/display/qdcm_calib_data_AA577_P_3_A0020_dsc_cmd_mode_panel.json:$(TARGET_COPY_OUT_ODM)/etc/display/qdcm_calib_data_AA577_P_3_A0020_dsc_cmd_mode_panel.json \
    vendor/oneplus/giulia/proprietary/odm/etc/mixer_paths.xml:$(TARGET_COPY_OUT_ODM)/etc/mixer_paths.xml \
    vendor/oneplus/giulia/proprietary/odm/etc/oprec_audrec_params/oprec_audrec_config.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_audrec_config.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/oprec_audrec_params/oprec_camback_calibration.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_camback_calibration.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/oprec_audrec_params/oprec_camfront_calibration.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_camfront_calibration.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID10_HE_App1.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID10_HE_App1.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID10_HE_App1.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID10_HE_App1.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID11_HE_Unprocess.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID11_HE_Unprocess.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID11_HE_Unprocess.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID11_HE_Unprocess.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID12_HE_VR.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID12_HE_VR.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID12_HE_VR.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID12_HE_VR.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID13_HE_USB.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID13_HE_USB.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID13_HE_USB.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID13_HE_USB.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID14_HE_USBApp1.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID14_HE_USBApp1.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID14_HE_USBApp1.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID14_HE_USBApp1.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID15_HE_BT.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID15_HE_BT.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID15_HE_BT.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID15_HE_BT.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID16_HE_BTApp1.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID16_HE_BTApp1.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID16_HE_BTApp1.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID16_HE_BTApp1.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID17_Concert.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID17_Concert.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID17_Concert.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID17_Concert.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID1_MIC_normal.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID1_MIC_normal.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID1_MIC_normal.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID1_MIC_normal.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID2_MIC_App1.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID2_MIC_App1.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID2_MIC_App1.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID2_MIC_App1.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID3_CamFront.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID3_CamFront.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID3_CamFront.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID3_CamFront.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID4_CamBack.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID4_CamBack.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID4_CamBack.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID4_CamBack.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID5_MIC_Conference.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID5_MIC_Conference.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID5_MIC_Conference.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID5_MIC_Conference.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID6_VR.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID6_VR.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID6_VR.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID6_VR.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID7_Interview.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID7_Interview.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID7_Interview.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID7_Interview.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID8_Unprocess.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID8_Unprocess.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID8_Unprocess.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID8_Unprocess.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID99_Bypass.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID99_Bypass.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID99_Bypass.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID99_Bypass.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID9_HE.bin:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID9_HE.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/oprec_audrec_params/oprec_record_ID9_HE.txt:$(TARGET_COPY_OUT_ODM)/etc/oprec_audrec_params/oprec_record_ID9_HE.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/resourcemanager.xml:$(TARGET_COPY_OUT_ODM)/etc/resourcemanager.xml \
    vendor/oneplus/giulia/proprietary/odm/etc/sensor/config/giulia_qrd_ois_system.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/giulia_qrd_ois_system.json \
    vendor/oneplus/giulia/proprietary/odm/etc/sensor/config/json_list:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/json_list \
    vendor/oneplus/giulia/proprietary/odm/etc/sensor/config/lanai_mtp_alsps.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/lanai_mtp_alsps.json \
    vendor/oneplus/giulia/proprietary/odm/etc/sensor/config/lanai_mtp_alsps_hw_tcs3720.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/lanai_mtp_alsps_hw_tcs3720.json \
    vendor/oneplus/giulia/proprietary/odm/etc/sensor/config/lanai_mtp_bmp5_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/lanai_mtp_bmp5_0.json \
    vendor/oneplus/giulia/proprietary/odm/etc/sensor/config/lanai_mtp_cct_rear.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/lanai_mtp_cct_rear.json \
    vendor/oneplus/giulia/proprietary/odm/etc/sensor/config/lanai_mtp_freefall.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/lanai_mtp_freefall.json \
    vendor/oneplus/giulia/proprietary/odm/etc/sensor/config/lanai_mtp_icm456xx_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/lanai_mtp_icm456xx_0.json \
    vendor/oneplus/giulia/proprietary/odm/etc/sensor/config/lanai_mtp_mmc56x3x.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/lanai_mtp_mmc56x3x.json \
    vendor/oneplus/giulia/proprietary/odm/etc/sensor/config/lanai_mtp_oplus_lay.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/lanai_mtp_oplus_lay.json \
    vendor/oneplus/giulia/proprietary/odm/etc/sensor/config/lanai_mtp_oplus_measurement.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/lanai_mtp_oplus_measurement.json \
    vendor/oneplus/giulia/proprietary/odm/etc/sensor/config/lanai_mtp_oplus_smart_prox.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/lanai_mtp_oplus_smart_prox.json \
    vendor/oneplus/giulia/proprietary/odm/etc/sensor/config/lanai_mtp_pocket.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/lanai_mtp_pocket.json \
    vendor/oneplus/giulia/proprietary/odm/etc/sensor/config/lux_aod.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/lux_aod.json \
    vendor/oneplus/giulia/proprietary/odm/etc/sensor/sensor_config.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/sensor_config.json \
    vendor/oneplus/giulia/proprietary/odm/etc/usecaseKvManager.xml:$(TARGET_COPY_OUT_ODM)/etc/usecaseKvManager.xml \
    vendor/oneplus/giulia/proprietary/odm/etc/wifi/kiwi/bdwlan.b0a:$(TARGET_COPY_OUT_ODM)/etc/wifi/kiwi/bdwlan.b0a \
    vendor/oneplus/giulia/proprietary/odm/etc/wifi/kiwi/bdwlan.b0c:$(TARGET_COPY_OUT_ODM)/etc/wifi/kiwi/bdwlan.b0c \
    vendor/oneplus/giulia/proprietary/odm/etc/wifi/kiwi/bdwlan.b0e:$(TARGET_COPY_OUT_ODM)/etc/wifi/kiwi/bdwlan.b0e \
    vendor/oneplus/giulia/proprietary/odm/etc/wifi/kiwi/bdwlan.b0i:$(TARGET_COPY_OUT_ODM)/etc/wifi/kiwi/bdwlan.b0i \
    vendor/oneplus/giulia/proprietary/odm/etc/wifi/kiwi/bdwlan.elf:$(TARGET_COPY_OUT_ODM)/etc/wifi/kiwi/bdwlan.elf \
    vendor/oneplus/giulia/proprietary/odm/etc/wifi/kiwi/regdb.bin:$(TARGET_COPY_OUT_ODM)/etc/wifi/kiwi/regdb.bin \
    vendor/oneplus/giulia/proprietary/odm/firmware/fastchg/23867/charging_hyper_mode_config.txt:$(TARGET_COPY_OUT_ODM)/firmware/fastchg/23867/charging_hyper_mode_config.txt \
    vendor/oneplus/giulia/proprietary/odm/firmware/fastchg/bms_heating_config.txt:$(TARGET_COPY_OUT_ODM)/firmware/fastchg/bms_heating_config.txt \
    vendor/oneplus/giulia/proprietary/odm/firmware/fastchg/charging_thermal_config_default.txt:$(TARGET_COPY_OUT_ODM)/firmware/fastchg/charging_thermal_config_default.txt \
    vendor/oneplus/giulia/proprietary/odm/firmware/fastchg/silicon_x24_smart_chg_config_table.txt:$(TARGET_COPY_OUT_ODM)/firmware/fastchg/silicon_x24_smart_chg_config_table.txt \
    vendor/oneplus/giulia/proprietary/odm/firmware/fastchg/smart_chg_config_table.txt:$(TARGET_COPY_OUT_ODM)/firmware/fastchg/smart_chg_config_table.txt \
    vendor/oneplus/giulia/proprietary/odm/firmware/sipa.bin:$(TARGET_COPY_OUT_ODM)/firmware/sipa.bin \
    vendor/oneplus/giulia/proprietary/odm/firmware/tp/23851/FW_S3910_BOE.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23851/FW_S3910_BOE.img \
    vendor/oneplus/giulia/proprietary/odm/firmware/tp/23851/FW_S3910_BOE_FAE.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23851/FW_S3910_BOE_FAE.img \
    vendor/oneplus/giulia/proprietary/odm/firmware/tp/23851/FW_S3910_BOE_HBP.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23851/FW_S3910_BOE_HBP.img \
    vendor/oneplus/giulia/proprietary/odm/firmware/tp/23851/FW_S3910_BOE_HBP_FAE.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23851/FW_S3910_BOE_HBP_FAE.img \
    vendor/oneplus/giulia/proprietary/odm/firmware/tp/23851/GloveDetect.tflite:$(TARGET_COPY_OUT_ODM)/firmware/tp/23851/GloveDetect.tflite \
    vendor/oneplus/giulia/proprietary/odm/firmware/tp/23851/LIB_S3910_BOE_HBP_TS_ALGO.so:$(TARGET_COPY_OUT_ODM)/firmware/tp/23851/LIB_S3910_BOE_HBP_TS_ALGO.so \
    vendor/oneplus/giulia/proprietary/odm/firmware/tp/23851/LIB_S3910_BOE_HBP_TS_ALGO_HWASAN.so:$(TARGET_COPY_OUT_ODM)/firmware/tp/23851/LIB_S3910_BOE_HBP_TS_ALGO_HWASAN.so \
    vendor/oneplus/giulia/proprietary/odm/firmware/tp/23851/LIB_S3910_BOE_HBP_TS_HAL.so:$(TARGET_COPY_OUT_ODM)/firmware/tp/23851/LIB_S3910_BOE_HBP_TS_HAL.so \
    vendor/oneplus/giulia/proprietary/odm/firmware/tp/23851/LIMIT_S3910_BOE.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23851/LIMIT_S3910_BOE.img \
    vendor/oneplus/giulia/proprietary/odm/firmware/tp/23851/LIMIT_S3910_BOE_AGING.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23851/LIMIT_S3910_BOE_AGING.img \
    vendor/oneplus/giulia/proprietary/odm/firmware/tp/23851/LIMIT_S3910_BOE_HBP.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23851/LIMIT_S3910_BOE_HBP.img \
    vendor/oneplus/giulia/proprietary/odm/firmware/tp/23851/LIMIT_S3910_BOE_HBP_AGING.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23851/LIMIT_S3910_BOE_HBP_AGING.img \
    vendor/oneplus/giulia/proprietary/odm/firmware/tp/23851/libIfp.so:$(TARGET_COPY_OUT_ODM)/firmware/tp/23851/libIfp.so \
    vendor/oneplus/giulia/proprietary/odm/firmware/tp/23851/libaifilm.so:$(TARGET_COPY_OUT_ODM)/firmware/tp/23851/libaifilm.so \
    vendor/oneplus/giulia/proprietary/odm/firmware/tp/23851/model.tflite:$(TARGET_COPY_OUT_ODM)/firmware/tp/23851/model.tflite \
    vendor/oneplus/giulia/proprietary/odm/firmware/tp/23851/sys_edge_touch_config.xml:$(TARGET_COPY_OUT_ODM)/firmware/tp/23851/sys_edge_touch_config.xml \
    vendor/oneplus/giulia/proprietary/odm/firmware/tp/23851/sys_touch_algo_feature_config.xml:$(TARGET_COPY_OUT_ODM)/firmware/tp/23851/sys_touch_algo_feature_config.xml \
    vendor/oneplus/giulia/proprietary/odm/firmware/tp/23851/sys_touch_function_feature_config.xml:$(TARGET_COPY_OUT_ODM)/firmware/tp/23851/sys_touch_function_feature_config.xml \
    vendor/oneplus/giulia/proprietary/odm/firmware/tp/23851/sys_touch_scene_config.xml:$(TARGET_COPY_OUT_ODM)/firmware/tp/23851/sys_touch_scene_config.xml \
    vendor/oneplus/giulia/proprietary/odm/firmware/tp/23867/libaifilm.so:$(TARGET_COPY_OUT_ODM)/firmware/tp/23867/libaifilm.so \
    vendor/oneplus/giulia/proprietary/odm/firmware/tp/23867/model.tflite:$(TARGET_COPY_OUT_ODM)/firmware/tp/23867/model.tflite \
    vendor/oneplus/giulia/proprietary/odm/firmware/tp/23868/libaifilm.so:$(TARGET_COPY_OUT_ODM)/firmware/tp/23868/libaifilm.so \
    vendor/oneplus/giulia/proprietary/odm/firmware/tp/23868/model.tflite:$(TARGET_COPY_OUT_ODM)/firmware/tp/23868/model.tflite \
    vendor/oneplus/giulia/proprietary/odm/firmware/tp/23869/libaifilm.so:$(TARGET_COPY_OUT_ODM)/firmware/tp/23869/libaifilm.so \
    vendor/oneplus/giulia/proprietary/odm/firmware/tp/23869/model.tflite:$(TARGET_COPY_OUT_ODM)/firmware/tp/23869/model.tflite \
    vendor/oneplus/giulia/proprietary/odm/firmware/ufs/SAMSUNG-KLUEG4RHHF-F0G1.bin:$(TARGET_COPY_OUT_ODM)/firmware/ufs/SAMSUNG-KLUEG4RHHF-F0G1.bin \
    vendor/oneplus/giulia/proprietary/odm/firmware/ufs/SAMSUNG-KLUFG8RHHD-B0G1.bin:$(TARGET_COPY_OUT_ODM)/firmware/ufs/SAMSUNG-KLUFG8RHHD-B0G1.bin \
    vendor/oneplus/giulia/proprietary/odm/firmware/ufs/SAMSUNG-KLUGGARHHD-B0G1.bin:$(TARGET_COPY_OUT_ODM)/firmware/ufs/SAMSUNG-KLUGGARHHD-B0G1.bin \
    vendor/oneplus/giulia/proprietary/odm/firmware/ufs/SKhynix-HN8T174EJKX075.bin:$(TARGET_COPY_OUT_ODM)/firmware/ufs/SKhynix-HN8T174EJKX075.bin \
    vendor/oneplus/giulia/proprietary/odm/firmware/ufs/SKhynix-HN8T274EJKX130.bin:$(TARGET_COPY_OUT_ODM)/firmware/ufs/SKhynix-HN8T274EJKX130.bin \
    vendor/oneplus/giulia/proprietary/odm/firmware/ufs/SKhynix-HN8T374ZJKX141.bin:$(TARGET_COPY_OUT_ODM)/firmware/ufs/SKhynix-HN8T374ZJKX141.bin \
    vendor/oneplus/giulia/proprietary/odm/firmware/ufs/move_target_ufs_fw_to_oplusreserve1.sh:$(TARGET_COPY_OUT_ODM)/firmware/ufs/move_target_ufs_fw_to_oplusreserve1.sh \
    vendor/oneplus/giulia/proprietary/odm/firmware/ufs/ufs_version_config.xml:$(TARGET_COPY_OUT_ODM)/firmware/ufs/ufs_version_config.xml \
    vendor/oneplus/giulia/proprietary/odm/lib64/camera/awb_parameter_qtech_s5kjn5_tele.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/awb_parameter_qtech_s5kjn5_tele.bin \
    vendor/oneplus/giulia/proprietary/odm/lib64/camera/awb_parameter_sunny_imx355.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/awb_parameter_sunny_imx355.bin \
    vendor/oneplus/giulia/proprietary/odm/lib64/camera/awb_parameter_sunny_imx480.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/awb_parameter_sunny_imx480.bin \
    vendor/oneplus/giulia/proprietary/odm/lib64/camera/awb_parameter_sunny_imx906.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/awb_parameter_sunny_imx906.bin \
    vendor/oneplus/giulia/proprietary/odm/lib64/camera/com.qti.sensormodule.qtech_s5kjn5_tele.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensormodule.qtech_s5kjn5_tele.bin \
    vendor/oneplus/giulia/proprietary/odm/lib64/camera/com.qti.sensormodule.qtech_s5kjn5_tele_short.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensormodule.qtech_s5kjn5_tele_short.bin \
    vendor/oneplus/giulia/proprietary/odm/lib64/camera/com.qti.sensormodule.sunny_imx355.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensormodule.sunny_imx355.bin \
    vendor/oneplus/giulia/proprietary/odm/lib64/camera/com.qti.sensormodule.sunny_imx480.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensormodule.sunny_imx480.bin \
    vendor/oneplus/giulia/proprietary/odm/lib64/camera/com.qti.sensormodule.sunny_imx906.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensormodule.sunny_imx906.bin \
    vendor/oneplus/giulia/proprietary/odm/lib64/camera/com.qti.tuned.qtech_s5kjn5_tele.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.tuned.qtech_s5kjn5_tele.bin \
    vendor/oneplus/giulia/proprietary/odm/lib64/camera/com.qti.tuned.sunny_imx355.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.tuned.sunny_imx355.bin \
    vendor/oneplus/giulia/proprietary/odm/lib64/camera/com.qti.tuned.sunny_imx480.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.tuned.sunny_imx480.bin \
    vendor/oneplus/giulia/proprietary/odm/lib64/camera/com.qti.tuned.sunny_imx906.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.tuned.sunny_imx906.bin \
    vendor/oneplus/giulia/proprietary/odm/lib64/camera/fdconfigpreview.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/fdconfigpreview.bin \
    vendor/oneplus/giulia/proprietary/odm/lib64/camera/fdconfigpreviewlite.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/fdconfigpreviewlite.bin \
    vendor/oneplus/giulia/proprietary/odm/lib64/camera/fdconfigvideo.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/fdconfigvideo.bin \
    vendor/oneplus/giulia/proprietary/odm/lib64/camera/fdconfigvideolite.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/fdconfigvideolite.bin \
    vendor/oneplus/giulia/proprietary/odm/vendor/firmware/uff_jv.b00:$(TARGET_COPY_OUT_ODM)/vendor/firmware/uff_jv.b00 \
    vendor/oneplus/giulia/proprietary/odm/vendor/firmware/uff_jv.b01:$(TARGET_COPY_OUT_ODM)/vendor/firmware/uff_jv.b01 \
    vendor/oneplus/giulia/proprietary/odm/vendor/firmware/uff_jv.b02:$(TARGET_COPY_OUT_ODM)/vendor/firmware/uff_jv.b02 \
    vendor/oneplus/giulia/proprietary/odm/vendor/firmware/uff_jv.b03:$(TARGET_COPY_OUT_ODM)/vendor/firmware/uff_jv.b03 \
    vendor/oneplus/giulia/proprietary/odm/vendor/firmware/uff_jv.b04:$(TARGET_COPY_OUT_ODM)/vendor/firmware/uff_jv.b04 \
    vendor/oneplus/giulia/proprietary/odm/vendor/firmware/uff_jv.b05:$(TARGET_COPY_OUT_ODM)/vendor/firmware/uff_jv.b05 \
    vendor/oneplus/giulia/proprietary/odm/vendor/firmware/uff_jv.b06:$(TARGET_COPY_OUT_ODM)/vendor/firmware/uff_jv.b06 \
    vendor/oneplus/giulia/proprietary/odm/vendor/firmware/uff_jv.b07:$(TARGET_COPY_OUT_ODM)/vendor/firmware/uff_jv.b07 \
    vendor/oneplus/giulia/proprietary/odm/vendor/firmware/uff_jv.b08:$(TARGET_COPY_OUT_ODM)/vendor/firmware/uff_jv.b08 \
    vendor/oneplus/giulia/proprietary/odm/vendor/firmware/uff_jv.mdt:$(TARGET_COPY_OUT_ODM)/vendor/firmware/uff_jv.mdt \
    vendor/oneplus/giulia/proprietary/odm/vendor/firmware/uff_spi.b00:$(TARGET_COPY_OUT_ODM)/vendor/firmware/uff_spi.b00 \
    vendor/oneplus/giulia/proprietary/odm/vendor/firmware/uff_spi.b01:$(TARGET_COPY_OUT_ODM)/vendor/firmware/uff_spi.b01 \
    vendor/oneplus/giulia/proprietary/odm/vendor/firmware/uff_spi.b02:$(TARGET_COPY_OUT_ODM)/vendor/firmware/uff_spi.b02 \
    vendor/oneplus/giulia/proprietary/odm/vendor/firmware/uff_spi.b03:$(TARGET_COPY_OUT_ODM)/vendor/firmware/uff_spi.b03 \
    vendor/oneplus/giulia/proprietary/odm/vendor/firmware/uff_spi.b04:$(TARGET_COPY_OUT_ODM)/vendor/firmware/uff_spi.b04 \
    vendor/oneplus/giulia/proprietary/odm/vendor/firmware/uff_spi.b05:$(TARGET_COPY_OUT_ODM)/vendor/firmware/uff_spi.b05 \
    vendor/oneplus/giulia/proprietary/odm/vendor/firmware/uff_spi.b06:$(TARGET_COPY_OUT_ODM)/vendor/firmware/uff_spi.b06 \
    vendor/oneplus/giulia/proprietary/odm/vendor/firmware/uff_spi.b07:$(TARGET_COPY_OUT_ODM)/vendor/firmware/uff_spi.b07 \
    vendor/oneplus/giulia/proprietary/odm/vendor/firmware/uff_spi.b08:$(TARGET_COPY_OUT_ODM)/vendor/firmware/uff_spi.b08 \
    vendor/oneplus/giulia/proprietary/odm/vendor/firmware/uff_spi.mdt:$(TARGET_COPY_OUT_ODM)/vendor/firmware/uff_spi.mdt \
    vendor/oneplus/giulia/proprietary/vendor/etc/card-defs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/card-defs.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/usecaseKvManager.xml:$(TARGET_COPY_OUT_VENDOR)/etc/usecaseKvManager.xml

PRODUCT_PACKAGES += \
    com.qti.sensor.imx355 \
    com.qti.sensor.imx480 \
    com.qti.sensor.imx906 \
    com.qti.sensor.s5kjn5_giulia \
    libOPAlgoCamGroupClassifier \
    libarcsoft_mcxmflpolicy \
    libdlrmsc \
    liboprec_audrec \
    liboprec_audrec_wrapper \
    libremosaiclib_s5k3p9 \
    libremosaiclib_s5kjn1 \
    libtfa98xx \
    libsixth_rx_v3
